name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.3.0
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Run tests
      run: cargo test --verbose
